package shared;

/**
* shared/FSInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from frontEnd/Interface.idl
* Friday, December 2, 2016 6:48:31 PM EST
*/

public final class FSInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public shared.FSInterface value = null;

  public FSInterfaceHolder ()
  {
  }

  public FSInterfaceHolder (shared.FSInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = shared.FSInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    shared.FSInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return shared.FSInterfaceHelper.type ();
  }

}
