package shared;


/**
* shared/FSInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from frontEnd/Interface.idl
* Saturday, December 3, 2016 2:14:02 AM EST
*/

public interface FSInterface extends FSInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FSInterface
