package shared;


/**
* shared/FSInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from frontEnd/Interface.idl
* Sunday, December 4, 2016 11:05:13 PM EST
*/

public interface FSInterface extends FSInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FSInterface
