package shared;


/**
* shared/FSInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from frontEnd/Interface.idl
* Sunday, December 4, 2016 11:05:13 PM EST
*/

public interface FSInterfaceOperations 
{
  int bookFlight (String city, String firsName, String lastName, String address, String phone, String destination, String date, String flightClass);
  String getBookedFlightCount (String city);
  int editRecord (String city, String recordId, String fieldName, String newValue);
  int addFlight (String city, String destination, String date, String ec, String bus, String fir);
  int removeFlight (String city, String recordId);
  int transferReservation (String city, String clientId, String currentCity, String otherCity);
} // interface FSInterfaceOperations
