package shared;


/**
* shared/FSInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from frontEnd/Interface.idl
* Friday, December 2, 2016 6:48:31 PM EST
*/

public interface FSInterface extends FSInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FSInterface
