package shared;


/**
* shared/FSInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from frontEnd/Interface.idl
* Friday, December 2, 2016 6:48:31 PM EST
*/

public interface FSInterfaceOperations 
{
  int bookFlight (String firsName, String lastName, String address, String phone, String destination, String date, int flightClass);
  String getBookedFlightCount ();
  int editRecord (String recordId, String fieldName, String newValue);
  int addFlight (String destination, String date, int ec, int bus, int fir);
  int removeFlight (int recordId);
  int transferReservation (String clientId, String currentCity, String otherCity);
} // interface FSInterfaceOperations
